# fly.toml app configuration file generated for socket-server-muddy-shadow-6983 on 2025-04-01T09:01:26+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'socket-server-muddy-shadow-6983'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
