# fly.toml app configuration file generated for socket-server-muddy-shadow-6983 on 2026-03-04T15:47:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'socket-server-muddy-shadow-6983'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
